apiVersion: v1
kind: Namespace
metadata:
  name: goland-qr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qr-backend-config
  namespace: goland-qr
data:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-goland-qr
  namespace: goland-qr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-goland-qr
  template:
    metadata:
      labels:
        app: postgres-goland-qr
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "${DB_USER}"
            - name: POSTGRES_PASSWORD
              value: "${DB_PASSWORD}"
            - name: POSTGRES_DB
              value: "${DB_NAME}"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-goland-qr
  namespace: goland-qr
spec:
  selector:
    app: postgres-goland-qr
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-backend
  namespace: goland-qr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-backend
  template:
    metadata:
      labels:
        app: qr-backend
    spec:
      hostAliases:
      - ip: "10.0.3.7"
        hostnames:
        - postgres.reto-ucu.net
      imagePullSecrets:
        - name: acr-cred
      containers:
        - name: qr-backend
          image: crretoxmas2024.azurecr.io/qr-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: qr-backend-config
            - secretRef:
                name: qr-backend-db-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: qr-backend-svc
  namespace: goland-qr
spec:
  selector:
    app: qr-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: qr-backend-route
  namespace: goland-qr
spec:
  ingressClassName: apisix
  http:
    - name: qr-backend-rule
      match:
        hosts:
          - goland-qr-backend-new.reto-ucu.net
        paths:
          - "/*"
          - "/"
      backends:
        - serviceName: qr-backend-svc
          servicePort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qr-backend-hpa
  namespace: goland-qr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qr-backend
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
