#!/usr/bin/env python3
"""
Genera el hash bcrypt de una contraseña

"""

import sys
import bcrypt


def get_password_hash(password: str) -> str:
    if not password:
        raise ValueError("password requerido para generar hash")
    hashed = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
    return hashed.decode("utf-8")


def main():
    password = "admin"
    if len(sys.argv) > 1:
        password = sys.argv[1]

    print(get_password_hash(password))


if __name__ == "__main__":
    main()
